watch_dirs: [
  '/Users/ngzax/Code/urbit/lush/app',
  '/Users/ngzax/Code/urbit/lush/gen',
  '/Users/ngzax/Code/urbit/lush/lib',
  '/Users/ngzax/Code/urbit/lush/tests'
]

excluded_files: [
  'readme.md'
]

desks: [
  '/base',
  '/base',
  '/base',
  '/base'
]

paths: [
  '/app',
  '/lib',
  '/lib',
  '/tests'
]

pier: '~/Urbit/pir/zod'
# pier: '~/Urbit/pir/tabwep-ponbud'
